import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Learning NEXT-JS",
    template: "%s | SneiTech"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{backgroundColor: "lightblue", padding: "1rem"}}>
          <h1>Header</h1>
        </header>
        {children}
        <footer style={{backgroundColor: "gray", padding: "1rem"}}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
